from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

from casio.v4_confluence_research import Candidate, load_features, metrics, replay
from casio.v4_edge_diagnose import core


DATA = Path("data/xauusd_m5_dukascopy_research.csv")
REPORT = Path("reports/v4-confluence/BACKTEST_2026_RM100_DUKASCOPY.md")
START = pd.Timestamp("2026-01-01T00:00:00Z")
END_EXCLUSIVE = pd.Timestamp("2027-01-01T00:00:00Z")
START_EQUITY_RM = 100.0
RISK_PCT = 0.01
CANDIDATE = Candidate(55, 0.60, 0.35, 6)


@dataclass
class MoneyStats:
    start_rm: float
    end_rm: float
    net_rm: float
    return_pct: float
    max_drawdown_rm: float
    max_drawdown_pct: float


def equity_stats(trades: pd.DataFrame) -> MoneyStats:
    equity = START_EQUITY_RM
    peak = equity
    max_dd_rm = 0.0
    max_dd_pct = 0.0

    if not trades.empty:
        for r in trades.sort_values("entry_time")["r"].astype(float):
            risk_rm = equity * RISK_PCT
            equity += risk_rm * r
            peak = max(peak, equity)
            dd_rm = peak - equity
            dd_pct = (dd_rm / peak * 100.0) if peak > 0 else 0.0
            max_dd_rm = max(max_dd_rm, dd_rm)
            max_dd_pct = max(max_dd_pct, dd_pct)

    return MoneyStats(
        start_rm=START_EQUITY_RM,
        end_rm=equity,
        net_rm=equity - START_EQUITY_RM,
        return_pct=(equity / START_EQUITY_RM - 1.0) * 100.0,
        max_drawdown_rm=max_dd_rm,
        max_drawdown_pct=max_dd_pct,
    )


def route_frame(base: pd.DataFrame, route: str) -> pd.DataFrame:
    x = core(base)
    if route == "LONG":
        x["short_setup"] = False
    elif route == "SHORT":
        x["long_setup"] = False
    elif route != "BOTH":
        raise ValueError(route)
    return x


def safe_pf(v: float) -> str:
    return "∞" if not np.isfinite(v) else f"{v:.2f}"


def fmt_money(v: float) -> str:
    return f"RM{v:,.2f}"


def monthly_rows(trades: pd.DataFrame, data_start: pd.Timestamp, data_end: pd.Timestamp) -> list[str]:
    rows: list[str] = []
    for month_start in pd.date_range("2026-01-01", "2026-12-01", freq="MS", tz="UTC"):
        month_end = month_start + pd.offsets.MonthBegin(1)
        visible_start = max(month_start, data_start)
        visible_end = min(month_end, data_end + pd.Timedelta(minutes=5))
        if visible_start >= visible_end:
            continue
        month_trades = trades[
            (trades["entry_time"] >= month_start) & (trades["entry_time"] < month_end)
        ].copy() if not trades.empty else trades
        if month_trades.empty:
            rows.append(f"| {month_start.strftime('%Y-%m')} | 0 | 0.00% | 0.000R | 0.00 | 0.000R |")
            continue
        m = metrics(month_trades, visible_start, visible_end)
        rows.append(
            f"| {month_start.strftime('%Y-%m')} | {m.trades} | {m.win_rate:.2f}% | "
            f"{m.expectancy_r:.3f}R | {safe_pf(m.profit_factor)} | {m.net_r:.3f}R |"
        )
    return rows


def playbook_rows(trades: pd.DataFrame, data_start: pd.Timestamp, data_end: pd.Timestamp) -> list[str]:
    if trades.empty:
        return ["| — | 0 | 0.00% | 0.000R | 0.00 |"]
    rows: list[str] = []
    for playbook, group in trades.groupby("playbook"):
        m = metrics(group, data_start, data_end)
        rows.append(
            f"| {playbook} | {m.trades} | {m.win_rate:.2f}% | {m.expectancy_r:.3f}R | {safe_pf(m.profit_factor)} |"
        )
    return rows


def main() -> None:
    features = load_features(DATA)
    base = features[(features.index >= START) & (features.index < END_EXCLUSIVE)].copy()
    if base.empty:
        raise RuntimeError("No initialized 2026 rows found in Dukascopy research CSV")

    data_start = base.index[0]
    data_end = base.index[-1]
    routes: dict[str, pd.DataFrame] = {}
    for route in ["BOTH", "LONG", "SHORT"]:
        routes[route] = replay(route_frame(base, route), CANDIDATE)

    lines = [
        "# CASIO v4 — 2026 Dukascopy RM100 Backtest",
        "",
        "Generated by GitHub Actions from `data/xauusd_m5_dukascopy_research.csv`.",
        "",
        "## Scope and assumptions",
        "",
        f"- Backtest window requested: **2026 only**.",
        f"- Available initialized data used: **{data_start.isoformat()} → {data_end.isoformat()}**.",
        "- Core trigger set: **BBMA re-entry + supply/demand rejection only**; standalone liquidity/FVG and breakout/retest triggers are disabled.",
        f"- Candidate: minimum score **{CANDIDATE.min_score}**, target **{CANDIDATE.target_r:.2f}R**, breakeven trigger **{CANDIDATE.be_trigger_r:.2f}R**, cooldown **{CANDIDATE.cooldown_bars} M5 bars**.",
        f"- Starting equity: **{fmt_money(START_EQUITY_RM)}**.",
        f"- Position sizing model: risk **{RISK_PCT * 100:.1f}% of current equity per trade**, compounded from each trade's R-result.",
        "- Intrabar collision rule: if stop and target are both touched inside one M5 bar, the replay assumes **stop first**.",
        "- **Spread, slippage, swap and broker commission are not deducted.** RM results are therefore a normalized risk-model projection, not broker-executable lot-size P&L.",
        "",
        "## Route summary",
        "",
        "| Route | Trades | Trades/wk | Win rate | Expectancy | PF | Net R | Max DD (R) | End equity | Net P/L | Return | Max RM DD |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]

    route_metrics: dict[str, object] = {}
    for route in ["BOTH", "LONG", "SHORT"]:
        t = routes[route]
        m = metrics(t, data_start, data_end)
        money = equity_stats(t)
        route_metrics[route] = (m, money)
        lines.append(
            f"| {route} | {m.trades} | {m.trades_per_week:.2f} | {m.win_rate:.2f}% | "
            f"{m.expectancy_r:.3f}R | {safe_pf(m.profit_factor)} | {m.net_r:.3f}R | "
            f"{m.max_drawdown_r:.3f}R | {fmt_money(money.end_rm)} | {fmt_money(money.net_rm)} | "
            f"{money.return_pct:.2f}% | {fmt_money(money.max_drawdown_rm)} ({money.max_drawdown_pct:.2f}%) |"
        )

    for route in ["BOTH", "LONG", "SHORT"]:
        t = routes[route]
        lines.extend([
            "",
            f"## {route} route — monthly results",
            "",
            "| Month | Trades | Win rate | Expectancy | PF | Net R |",
            "|---|---:|---:|---:|---:|---:|",
            *monthly_rows(t, data_start, data_end),
            "",
            f"### {route} route — playbook breakdown",
            "",
            "| Playbook | Trades | Win rate | Expectancy | PF |",
            "|---|---:|---:|---:|---:|",
            *playbook_rows(t, data_start, data_end),
        ])

    both_m, both_money = route_metrics["BOTH"]
    lines.extend([
        "",
        "## Notes",
        "",
        "This is an out-of-sample-style calendar slice report, not a guarantee of future performance. The RM100 equity path is derived from R-multiples with fixed 1% current-equity risk; actual XAUUSD lot sizing depends on broker contract size, leverage, minimum lot and transaction costs.",
        "",
        f"Combined 2026 slice result: **{both_m.trades} trades**, **{both_m.win_rate:.2f}% win rate**, **{both_m.expectancy_r:.3f}R expectancy**, **PF {safe_pf(both_m.profit_factor)}**, ending at **{fmt_money(both_money.end_rm)}** before execution costs.",
        "",
    ])

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(REPORT.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
